"""
core/exporter.py
Exports extracted profiles to SQL, CSV, or Excel
using a user-defined or default field mapping/structure.
"""
import csv, json, io
from datetime import datetime


# ── Default fields (all 40) ───────────────────────────
DEFAULT_FIELDS = [
    "Name","Gender","DOB","Age","TOB","POB","Maritalstatus","Education",
    "EducationDetails","Occupation","Employedin","Annualincome","Religion",
    "Caste","Subcaste","Gothram","Language","Star","Moonsign","Height",
    "Weight","BloodGroup","Complexion","Diet","Smoke","Drink","Address",
    "City","Dist","State","Country","Pincode","Mobile","Phone",
    "Fathername","Mothersname","Fathersoccupation","Mothersoccupation",
    "noofbrothers","noofsisters","FamilyType","FamilyStatus","FamilyValues",
    "PartnerExpectations","Hobbies","Interests","Religion","Residencystatus"
]


def _header():
    return (
        f"-- Auto-generated by Matrimony AI Agent\n"
        f"-- Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n"
    )


# ── SQL ───────────────────────────────────────────────
def to_sql(profiles, table="register", fields=None):
    """Generate SQL INSERT statements."""
    lines = [_header()]
    for i, p in enumerate(profiles):
        # Apply field mapping / filter
        row = _apply_fields(p, fields)
        cols, vals = [], []
        for k, v in row.items():
            if v is not None and str(v).strip():
                cols.append(f"`{k}`")
                escaped = str(v).replace("'", "''")
                vals.append(f"'{escaped}'")
        if cols:
            name = p.get("Name", f"Profile {i+1}")
            lines.append(f"-- {name}\n")
            lines.append(f"INSERT INTO `{table}` ({', '.join(cols)}) VALUES ({', '.join(vals)});\n\n")
    return "".join(lines)


# ── CSV ───────────────────────────────────────────────
def to_csv(profiles, fields=None):
    """Generate CSV string."""
    if not profiles:
        return ""
    rows = [_apply_fields(p, fields) for p in profiles]
    all_keys = list(rows[0].keys()) if rows else []

    out = io.StringIO()
    writer = csv.DictWriter(out, fieldnames=all_keys, extrasaction='ignore', lineterminator='\n')
    writer.writeheader()
    for row in rows:
        writer.writerow({k: (v if v is not None else '') for k, v in row.items()})
    return out.getvalue()


# ── Excel ─────────────────────────────────────────────
def to_excel(profiles, fields=None, output_path=None):
    """Generate formatted Excel file using openpyxl."""
    from openpyxl import Workbook
    from openpyxl.styles import (Font, PatternFill, Alignment,
                                  Border, Side, GradientFill)
    from openpyxl.utils import get_column_letter

    wb = Workbook()
    ws = wb.active
    ws.title = "Profiles"

    if not profiles:
        ws['A1'] = "No profiles extracted"
        wb.save(output_path)
        return

    rows = [_apply_fields(p, fields) for p in profiles]
    headers = list(rows[0].keys())

    # ── Header row styling ────────────────────────────
    header_fill = PatternFill("solid", fgColor="1A1A2E")
    accent_fill = PatternFill("solid", fgColor="F0A500")
    alt_fill    = PatternFill("solid", fgColor="F8F9FA")
    thin_border = Border(
        bottom=Side(style='thin', color='E0E0E0'),
        right=Side(style='thin', color='E0E0E0')
    )

    for col_idx, header in enumerate(headers, 1):
        cell = ws.cell(row=1, column=col_idx, value=header)
        cell.font      = Font(bold=True, color="FFFFFF", name="Arial", size=10)
        cell.fill      = header_fill
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cell.border    = thin_border

    ws.row_dimensions[1].height = 28

    # ── Data rows ─────────────────────────────────────
    for row_idx, row_data in enumerate(rows, 2):
        is_alt = row_idx % 2 == 0
        for col_idx, key in enumerate(headers, 1):
            val  = row_data.get(key)
            cell = ws.cell(row=row_idx, column=col_idx, value=val if val is not None else "")
            cell.font      = Font(name="Arial", size=9)
            cell.alignment = Alignment(vertical="center", wrap_text=False)
            cell.border    = thin_border
            if is_alt:
                cell.fill = alt_fill

    # ── Column widths ─────────────────────────────────
    wide = {"Name":22,"Address":32,"PartnerExpectations":30,"Education":25,
            "EducationDetails":28,"Occupation":20,"Mobile":16,"DOB":14}
    for col_idx, header in enumerate(headers, 1):
        w = wide.get(header, 16)
        ws.column_dimensions[get_column_letter(col_idx)].width = w

    # ── Freeze header row ─────────────────────────────
    ws.freeze_panes = "A2"

    # ── Auto filter ───────────────────────────────────
    ws.auto_filter.ref = ws.dimensions

    # ── Summary sheet ─────────────────────────────────
    ws2 = wb.create_sheet("Summary")
    ws2['A1'] = "Matrimony AI Agent — Export Summary"
    ws2['A1'].font = Font(bold=True, size=14, name="Arial", color="1A1A2E")
    ws2['A3'] = "Generated"; ws2['B3'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    ws2['A4'] = "Total Profiles"; ws2['B4'] = len(profiles)
    ws2['A5'] = "Fields Exported"; ws2['B5'] = len(headers)
    ws2['A6'] = "Fields"; ws2['B6'] = ", ".join(headers)

    for cell in [ws2['A3'],ws2['A4'],ws2['A5'],ws2['A6']]:
        cell.font = Font(bold=True, name="Arial", size=10)
    for cell in [ws2['B3'],ws2['B4'],ws2['B5'],ws2['B6']]:
        cell.font = Font(name="Arial", size=10)

    ws2.column_dimensions['A'].width = 20
    ws2.column_dimensions['B'].width = 60

    wb.save(output_path)
    return output_path


# ── JSON ──────────────────────────────────────────────
def to_json(profiles, fields=None):
    rows = [_apply_fields(p, fields) for p in profiles]
    return json.dumps(rows, indent=2, ensure_ascii=False)


# ── Field mapping helper ──────────────────────────────
def _apply_fields(profile, fields):
    """
    Apply user-defined field structure to a profile.
    fields can be:
      - None → return profile as-is
      - list of strings → pick/reorder fields
      - list of dicts [{from: "Name", to: "FullName"}, ...] → rename fields
      - dict {output_field: source_field} → rename mapping
    """
    if not fields:
        return {k: v for k, v in profile.items() if v is not None}

    result = {}

    # Dict mapping: {output: source}
    if isinstance(fields, dict):
        for out_key, src_key in fields.items():
            result[out_key] = profile.get(src_key)
        return result

    # List of dicts: [{from:.., to:..}] or [{label:.., field:..}]
    if isinstance(fields, list) and fields and isinstance(fields[0], dict):
        for item in fields:
            src = item.get("from") or item.get("field") or item.get("source")
            dst = item.get("to")   or item.get("label") or src
            if src:
                result[dst] = profile.get(src)
        return result

    # Simple list of field names
    if isinstance(fields, list):
        for f in fields:
            result[f] = profile.get(f)
        return result

    return profile
