from datetime import datetime

def to_sql_insert(profile, table="register"):
    cols, vals = [], []
    for k, v in profile.items():
        if v is not None:
            cols.append(f"`{k}`")
            escaped = str(v).replace("'", "''")
            vals.append(f"'{escaped}'")
    return f"INSERT INTO `{table}` ({', '.join(cols)}) VALUES ({', '.join(vals)});"

def sql_file_header(source, total):
    return (
        f"-- Auto-generated by Matrimony AI Agent\n"
        f"-- Source  : {source}\n"
        f"-- Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        f"-- Pages   : {total}\n\n"
    )
